#
# Module manifest for module 'SecretManagement.Sops'
#
# Generated by: SecretManagement.Sops Contributors
#
# Generated on: 12/30/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'SecretManagement.Sops.psm1'

    # Version number of this module.
    ModuleVersion = '0.3.0'

    # Supported PSEditions
    CompatiblePSEditions = 'Desktop', 'Core'

    # ID used to uniquely identify this module
    GUID = 'd9134320-f7b9-4391-8f35-298108b60fba'

    # Author of this module
    Author = 'SecretManagement.Sops Contributors'

    # Company or vendor of this module
    CompanyName          = 'Community'

    # Copyright statement for this module
    Copyright = '(c) 2025 SecretManagement.Sops Contributors. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'A PowerShell SecretManagement extension vault for Mozilla SOPS (Secrets OPerationS). Provides native PowerShell integration for SOPS-encrypted secrets with support for Azure Key Vault, age, and Kubernetes Secret manifests.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @(@{ModuleName = 'Microsoft.PowerShell.SecretManagement'; ModuleVersion = '1.1.0'; })

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @('.\SecretManagement.Sops.Extension\SecretManagement.Sops.Extension.psd1')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = 'Get-SecretIndex', 'Get-SecretIndexEntry', 'Invoke-SopsDecrypt',
    'Invoke-SopsEncrypt', 'Invoke-SopsSet', 'Invoke-SopsUnset',
    'New-KubernetesSecret', 'Resolve-SecretName', 'Test-SopsAvailable'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = 'SecretManagement', 'SOPS', 'Secrets', 'Encryption', 'Kubernetes', 'GitOps', 'FluxCD', 'AzureKeyVault', 'age'

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = '## 0.3.0 (2025-01-30)

### Added
- Full SecretManagement vault implementation for SOPS with read/write support
- Get-Secret: Retrieve and decrypt SOPS-encrypted secrets
- Set-Secret: Create and update secrets with SOPS encryption
- Remove-Secret: Delete secrets from SOPS files
- Kubernetes Secret manifest detection and intelligent parsing
- Data key extraction for Kubernetes Secrets (e.g., ''secret-name/data-key'')
- Namespace support with collision detection for organized secret management
- Multiple naming strategies: RelativePath, FileName, KubernetesMetadata
- PSCredential auto-conversion for username/password pairs
- Integration with Azure Key Vault, age, AWS KMS, GCP KMS, and PGP encryption backends
- Comprehensive error messages with actionable troubleshooting hints
- Patch-first approach for Set-Secret to preserve file structure and comments

### Current Limitations
- YAML format only (JSON and dotenv support planned for future releases)
- No caching (every operation invokes SOPS binary)
- No Unlock-SecretVault implementation

### Requirements
- PowerShell 5.1 or later (PowerShell 7+ recommended)
- Microsoft.PowerShell.SecretManagement 1.1.0 or later
- SOPS binary in PATH (https://github.com/getsops/sops/releases)
- Encryption backend: Azure CLI, age, AWS credentials, GCP credentials, or GPG'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

